Binance.Net/Objects/Binance24hPrice.cs

`firstId` no longer contains spelling error on api (`fristId`).
With the existing overriding of FirstId property, the property is set to default `0`.
Verified here: https://www.binance.com/api/v1/ticker/24hr?symbol=XRPBTC

Update Binance24hPrice FirstId JsonProperty name

---

Binance.Net/BinanceClientOptions.cs
Binance.Net/BinanceSocketClient.cs
Binance.Net/Objects/BinanceCombinedStream.cs

Today when we need to listen to several markets at the same time, a socket connection is open for each market, this does not work very well in Binance, it does not let many socket connections be made in a small timeout, but it recommends that when you need listen to many different markets at the same time you pass the markets you need via query string in the websocket connection link.
My implementation supports this. I added support to be able to listen from several markets at the same time in the following methods: `SubscribeToCombinedDepthStream`, `SubscribeToCombinedTradesStream `and `SubscribeToCombinedPartialBookDepthStream` in the `BinanceSocketClient` object, you receive from this methods the object `BinanceCombinedStream` its the Stream name received, and Data received from …

Added combined stream on one socket connection

---

Binance.Net/BinanceClient.cs

In the latest version of this package, the client is unable to make a request if the local time is over 1000ms behind the server time.
This fix takes the absolute value of the offset calculation so an adjustment can be made.
Reference Issue: https://github.com/JKorf/Binance.Net/issues/175
Example of error in use:
Credit to @Cooksauce for this fix!

Fixed Server Time Offset Calculation

---

Binance.Net/Binance.Net.xml
Binance.Net/Objects/Futures/MarketData/BinanceFuturesMarkPrice.cs

Mark price endpoint for both USDT and Coin-M futures have indexPrice field in response, so I've added it to the model.
Reference:
[https://binance-docs.github.io/apidocs/futures/en/#mark-price](https://binance-docs.github.io/apidocs/futures/en/#mark-price)
[https://fapi.binance.com/fapi/v1/premiumIndex](https://fapi.binance.com/fapi/v1/premiumIndex)
[https://dapi.binance.com/dapi/v1/premiumIndex](https://dapi.binance.com/dapi/v1/premiumIndex)

Added IndexPrice field to BinanceFuturesMarkPrice

---

Binance.Net/Binance.Net.xml
Binance.Net/SubClients/Margin/BinanceClientMarginIsolatedUserStream.cs
Binance.Net/SubClients/Margin/BinanceClientMarginUserStream.cs
Binance.Net/SubClients/Spot/BinanceClientSpotUserStream.cs

A small copy paste error in the method documentation.
https://binance-docs.github.io/apidocs/spot/en/#user-data-streams

fix method documentation: "Invalidate listen key" instead of "Keep alive"

---

Binance.Net/Objects/Spot/MarginData/BinanceInterestRateHistory.cs

Fixes `DailyInterest` in `BinanceInterestRateHistory` returning `0`

Deserialization Fix

---

Binance.Net/Binance.Net.xml
Binance.Net/Interfaces/SocketSubClient/IBinanceSocketClientBase.cs
Binance.Net/SocketSubClients/BinanceSocketClientFutures.cs
Binance.Net/SocketSubClients/BinanceSocketClientFuturesCoin.cs
Binance.Net/SocketSubClients/BinanceSocketClientFuturesUsdt.cs
Binance.Net/SocketSubClients/BinanceSocketClientSpot.cs

Allows the passing of multiple intervals in SubscribeToKlineUpdatesAsync.
* Extended the IBinanceSocketClientBase with additional method to allow passing multiple intervals for a Symbols
* Implemented methods in ClientSpot, ClientFuturesCoin & ClientFuturesUsdt
* Updated SubscribeToKlineUpdatesAsync to allow for generation of multiple intervals into subscribe command

Allow multiple intervals for kline subscription

---

Binance.Net/Binance.Net.xml
Binance.Net/Interfaces/SubClients/IBinanceClientGeneral.cs
Binance.Net/SubClients/BinanceClientGeneral.cs

Dust log supports startTime and endTime not mandatory parameters: [binance-docs](https://binance-docs.github.io/apidocs/spot/en/#dustlog-user_data).

Add startTime and endTime not mandatory parameter to GetDustLogAsync

---

Binance.Net/Binance.Net.xml
Binance.Net/Converters/UniversalTransferTypeConverter.cs
Binance.Net/Enums/UniversalTransferType.cs

According to changes in Binance API.
> Update endpoint for Wallet:
New transfer types MAIN_FUNDING,FUNDING_MAIN,FUNDING_UMFUTURE,UMFUTURE_FUNDING,MARGIN_FUNDING,FUNDING_MARGIN,FUNDING_CMFUTUREand CMFUTURE_FUNDING added in Universal Transfer endpoint POST /sapi/v1/asset/transfer and GET /sapi/v1/asset/transfer to support trasnfer assets among funding account and other accounts
As the C2C account, Binance Payment, Binance Card and other businesses account are merged into a Funding account, transfer types MAIN_C2C,C2C_MAIN,C2C_UMFUTURE,C2C_MINING,UMFUTURE_C2C,MINING_C2C,MARGIN_C2C,C2C_MARGIN,MAIN_PAYand PAY_MAIN will be discontinued in Universal Transfer endpoint POST /sapi/v1/asset/transfer and GET /sapi/v1/asset/transfer on November 04, 2021 08:00 AM UTC

UniversalTransferType align to latest

---

Binance.Net/Clients/GeneralApi/BinanceClientGeneralApiSubAccount.cs
Binance.Net/Converters/FuturesAccountTypeConverter.cs
Binance.Net/Enums/FuturesAccountType.cs
Binance.Net/Interfaces/Clients/GeneralApi/IBinanceClientGeneralApiSubAccount.cs
Binance.Net/Objects/Models/Spot/SubAccountData/BinanceSubAccountFuturesDetailsV2.cs
Binance.Net/Objects/Models/Spot/SubAccountData/BinanceSubAccountFuturesPositionRiskV2.cs

support the v2 endpoint: https://binance-docs.github.io/apidocs/spot/en/#get-detail-on-sub-account-39-s-futures-account-v2-for-master-account

add support for the v2 sub account futures details endpoint

---

Binance.Net.UnitTests/JsonResponses/Spot/SubAccount/GetUniversalTransferHistory.txt
Binance.Net/Clients/GeneralApi/BinanceClientGeneralApiSubAccount.cs
Binance.Net/Objects/Models/Spot/SubAccountData/BinanceSubAccountFuturesDetailsV2.cs
Binance.Net/Objects/Models/Spot/SubAccountData/BinanceSubAccountUniversalTransferTransaction.cs

This fixes GetSubAccountTransferHistoryForSubAccountAsync and GetUniversalTransferHistoryAsync. 
The binance api docs are not correct for the json response returned in GetUniversalTransferHistory.txt, I've let them know and they are going to correct. 
The behaviour of the client when requesting universal transfer history before this change was to return no results, this PR fixes this.

Fix GetSubAccountTransferHistoryForSubAccountAsync and GetUniversalTransferHistoryAsync

---

Binance.Net/Objects/Models/Spot/SubAccountData/BinanceSubAccountStatus.cs

As mobile numbers should be strings, and can be null which breaks this library

Fix Mobile number from long to string

---

Binance.Net/Clients/SpotApi/BinanceClientSpotApiAccount.cs

according to https://binance-docs.github.io/apidocs/spot/en/#query-repay-record-user_data it's name must be 'current' not 'page'

wrong pagination parameter name

---

Binance.Net/Converters/SymbolFilterTypeConverter.cs
Binance.Net/Enums/SymbolFilterType.cs
Binance.Net/Objects/Models/Spot/BinanceSymbol.cs
Binance.Net/Objects/Models/Spot/BinanceSymbolFilter.cs

#1059
Trailing Stops have been enabled.
This is a type of algo order where the activation is based on a percentage of a price change in the market using the new parameter trailingDelta.
This can only used with any of the following order types: STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, TAKE_PROFIT_LIMIT.
The trailingDelta parameter will be done in Basis Points or BIPS.
For example: a STOP_LOSS SELL order with a trailingDelta of 100 will trigger after a price decrease of 1%. (100 / 10,000 => 0.01 => 1%)
When used in combination with OCO Orders, the trailingDelta will determine when the contingent leg of the OCO will trigger.
When trailingDelta is used in combination with stopPrice, once the stopPrice condition is met, the trailing stop starts tracking the price change from the stopPrice …

Add Trailing Delta

---

Binance.Net/Converters/SymbolFilterConverter.cs

Fix Trailing Delta Json Writer
Before: 
```cs
{
"filterType": "TRAILING_DELTA",
},
```
After:
```cs
{
"filterType": "TRAILING_DELTA",
"maxTrailingAboveDelta": 2000,
"maxTrailingBelowDelta": 2000,
"minTrailingAboveDelta": 10,
"minTrailingBelowDelta": 10
},
```

Fix Trailing Delta Json Writer

---

Binance.Net/Clients/SpotApi/BinanceClientSpotApiTrading.cs

Fixes `GetPayTradeHistoryAsync`
```cs
parameters.AddOptionalParameter("startTimestamp", DateTimeConverter.ConvertToMilliseconds(startTime));
parameters.AddOptionalParameter("endTimestamp", DateTimeConverter.ConvertToMilliseconds(endTime));
```
=>
```cs
parameters.AddOptionalParameter("startTime", DateTimeConverter.ConvertToMilliseconds(startTime));
parameters.AddOptionalParameter("endTime", DateTimeConverter.ConvertToMilliseconds(endTime));
```

Fixes `GetPayTradeHistoryAsync`

---

Binance.Net/Clients/SpotApi/BinanceClientSpotApiTrading.cs

Changed `page` parameter to `current` based on the Binance documentation.
Docs:
https://binance-docs.github.io/apidocs/spot/en/#get-staking-product-position-user_data
https://binance-docs.github.io/apidocs/spot/en/#get-staking-history-user_data

Fixed staking page parameter of positions and history

---

Binance.Net/Binance.Net.xml
Binance.Net/Clients/SpotApi/BinanceClientSpotApiExchangeData.cs
Binance.Net/Interfaces/Clients/SpotApi/IBinanceClientSpotApiExchangeData.cs

```
Changes to GET /api/v3/exchangeInfo
New optional parameter permissions added to display all symbols with the permissions matching the parameter provided. (eg.SPOT, MARGIN, LEVERAGED)
If not provided, the default value will be ["SPOT","MARGIN", "LEVERAGED"].
This means the request GET /api/v3/exchangeInfo without any parameters will show all symbols that can be used for SPOT,MARGIN and/or LEVERAGED trading.
To search for symbols that can be traded on other permissions (e.g. TRD_GRP_004, etc), then this needs to be searched for explicitly. (e.g.permissions=TRD_GRP_004)
Cannot be combined with symbol or symbols
```
https://github.com/JKorf/Binance.Net/issues/1154

GetExchangeInfoAsync based on AccountType

---

Binance.Net/Binance.Net.xml
Binance.Net/Clients/GeneralApi/BinanceClientGeneralApiSavings.cs
Binance.Net/Interfaces/Clients/GeneralApi/IBinanceClientGeneralApiSavings.cs

Retrieving the flexible product positions resulted in a maximum of `50` positions.
Binance's [documentation ](https://binance-docs.github.io/apidocs/spot/en/#get-flexible-product-position-user_data) hasn't been updated with the pagination parameters `current` and `size` but it seems to be the way to be able to retrieve more than 50 positions.

Added pagination to flexible product positions

---

README.md

I just noticed if you click these it opens the image in a new tab so it should probably go somewhere useful instead
Add Nuget link to readme https://www.nuget.org/packages/Binance.Net

Add Nuget link to README

---

Binance.Net/Clients/SpotApi/BinanceClientSpotApiExchangeData.cs

page 404 of 
```
https://www.binance.com/exchange-api/v2/public/asset-service/product/get-products
```
changed to 
https://www.binance.com/bapi/asset/v2/public/asset-service/product/get-products

fixed the spot exchange info stopped working.

---

Binance.Net/Binance.Net.xml
Binance.Net/Clients/SpotApi/BinanceSocketClientSpotApiTrading.cs
Binance.Net/Interfaces/Clients/SpotApi/IBinanceSocketClientSpotApiTrading.cs

Change type of orderId parameter in GetOrderAsync and CancelOrderAsync
Your code has incorrect type of orderId parameter in GetOrderAsync and CancelOrderAsync in IBinanceSocketClientSpotApiTrading.  
int? is specified instead of long.
To see the problem you can place an order or get the real clientId from an existing order. For example, the real identifier (2712825989) cannot be converted to Int32

Change orderId  type

---

Binance.Net/Clients/SpotApi/BinanceRestClientSpotApiExchangeData.cs

The check has been removed because if values for both fromAsset and toAsset are not defined, only partial token pairs will be returned.
Info - https://binance-docs.github.io/apidocs/spot/en/#list-all-convert-pairs

Fix - List All Convert Pairs

---

Binance.Net/Clients/UsdFuturesApi/BinanceRestClientUsdFuturesApiTrading.cs

This pull request fixes the issue where the `goodTillDate` timestamp for USD Futures limit orders was incorrectly sent in seconds, causing the order to fail. The timestamp is now correctly formatted in milliseconds.
**Related Issue:**
- Fixes #1386 
**Changes:**
- Changed `AddOptionalSeconds` to `AddOptionalMilliseconds` in the `BinanceRestClientUsdFuturesApiTrading`.
Thank you for considering this pull request!

Refs #1386: Correct goodTillDate timestamp format to milliseconds

---

Binance.Net/Binance.Net.xml
Binance.Net/Clients/GeneralApi/BinanceRestClientGeneralApi.cs
Binance.Net/Clients/GeneralApi/BinanceRestClientGeneralApiCopyTrading.cs
Binance.Net/Interfaces/Clients/GeneralApi/IBinanceRestClientGeneralApi.cs
Binance.Net/Interfaces/Clients/GeneralApi/IBinanceRestClientGeneralApiCopyTrading.cs
Binance.Net/Objects/Models/Spot/CopyTrading/BinanceCopyTradingLeadSymbol.cs
Binance.Net/Objects/Models/Spot/CopyTrading/BinanceCopyTradingUserStatus.cs

Docs:
https://binance-docs.github.io/apidocs/spot/en/#copy-trading-endpoints
https://binance-docs.github.io/apidocs/spot/en/#get-futures-lead-trading-symbol-whitelist-user_data

Added copy trading endpoints

---

Binance.Net.UnitTests/RestRequestTests.cs
Binance.Net/Binance.Net.xml
Binance.Net/Clients/UsdFuturesApi/BinanceRestClientUsdFuturesApiTrading.cs
Binance.Net/Clients/UsdFuturesApi/BinanceSocketClientUsdFuturesApiTrading.cs
Binance.Net/Interfaces/Clients/UsdFuturesApi/IBinanceRestClientUsdFuturesApiTrading.cs
Binance.Net/Interfaces/Clients/UsdFuturesApi/IBinanceSocketClientUsdFuturesApiTrading.cs
Binance.Net/Objects/Models/Futures/BinanceFuturesBatchEditOrder.cs

This adds a `PriceMatch` parameter to the USD-futures order editing methods (both REST and WS). This is useful for "chasing" limit orders to prevent market order fees.
Submitting as a draft for feedback.

Add PriceMatch parameter to order editing

---

Binance.Net/Binance.Net.xml
Binance.Net/Clients/UsdFuturesApi/BinanceSocketClientUsdFuturesApiExchangeData.cs
Binance.Net/Clients/UsdFuturesApi/BinanceSocketClientUsdFuturesApiShared.cs
Binance.Net/Interfaces/Clients/UsdFuturesApi/IBinanceSocketClientUsdFuturesApiExchangeData.cs

Added support for premium index kline subscription. This isn't provided in the binance documentation, but inspecting element on the page https://www.binance.com/en/futures/funding-history/perpetual/index shows that this is what they use to pull premium index k-lines.

Create support for premium index klines

---

Binance.Net/Binance.Net.xml
Binance.Net/Clients/SpotApi/BinanceRestClientSpotApiTrading.cs
Binance.Net/Interfaces/Clients/SpotApi/IBinanceRestClientSpotApiTrading.cs

Added orderId parameter to Binance.Net.Clients.SpotApi.IBinanceRestClientSpotApiTrading.GetMarginUserTradesAsync.
(based on Binance API call: 'GET /sapi/v1/margin/myTrades'), which has an orderId search parameter.

Added orderId parameter to Spot.GetMarginUserTradesAsync

---

Binance.Net/Clients/SpotApi/BinanceRestClientSpotApiTrading.cs
Binance.Net/Interfaces/Clients/SpotApi/IBinanceRestClientSpotApiTrading.cs

Added missing listClientOrderId parameter [Issue 1491](https://github.com/JKorf/Binance.Net/issues/1491#issue-2958882807)
https://developers.binance.com/docs/binance-spot-api-docs/rest-api/trading-endpoints#new-order-list---oco-trade

Add listClientOrderId parameter to PlaceOcoOrderListAsync method (#1491)

---

Binance.Net/Clients/GeneralApi/BinanceRestClientGeneralApiNft.cs
Binance.Net/Enums/NftOrderType.cs
Binance.Net/Interfaces/Clients/GeneralApi/IBinanceRestClientGeneralApiNft.cs
Binance.Net/Objects/Models/BinanceListRecords.cs
Binance.Net/Objects/Models/Spot/Nft/BinanceNftAsset.cs
Binance.Net/Objects/Models/Spot/Nft/BinanceNftDeposit.cs
Binance.Net/Objects/Models/Spot/Nft/BinanceNftTransaction.cs
Binance.Net/Objects/Models/Spot/Nft/BinanceNftWithdraw.cs

- Implemented `BinanceRestClientGeneralApiNft` class for handling NFT-related endpoints
- Added Interfaces:
- `IBinanceRestClientGeneralApiNft`
- Added models:
- `BinanceNftAsset`
- `BinanceNftDeposit`
- `BinanceNftTransaction`
- `BinanceNftWithdraw`
- `BinanceListRecords`
- Added enums:
- `NftOrderType` 
- DOCS: https://developers.binance.com/docs/nft/rest-api

Added NFT Endpoints

---

Binance.Net/Clients/SpotApi/BinanceRestClientSpotApiExchangeData.cs
Binance.Net/Enums/MarginInventoryType.cs
Binance.Net/Interfaces/Clients/SpotApi/IBinanceRestClientSpotApiExchangeData.cs
Binance.Net/Objects/Models/Spot/Margin/BinanceCrossMarginProLiabilityCoinLeverageBracket.cs
Binance.Net/Objects/Models/Spot/Margin/BinanceIsolatedMarginTier.cs
Binance.Net/Objects/Models/Spot/Margin/BinanceMarginAvailableInventory.cs

Added support for missing margin market data endpoints:
- [Query Isolated Margin Tier Data](https://developers.binance.com/docs/margin_trading/market-data/Query-Isolated-Margin-Tier-Data)
- [Query Margin Available Inventory](https://developers.binance.com/docs/margin_trading/market-data/Query-margin-avaliable-inventory)
- [Query Liability Coin Leverage Bracket in Cross Margin Pro Mode](https://developers.binance.com/docs/margin_trading/market-data/Query-Liability-Coin-Leverage-Bracket-in-Cross-Margin-Pro-Mode)

Added missing margin market data endpoints

---

Binance.Net/Clients/CoinFuturesApi/BinanceSocketClientCoinFuturesApiAccount.cs

I deleted the extra path stream because there was a duplication of the path :wss://stream.binance.com/stream/stream

fx path SubscribeToUserDataUpdatesAsync for coin

---

Binance.Net/Clients/SpotApi/BinanceRestClientSpotApiAccount.cs

Updated request weight from 3000 to 1500 for methods:
- `MarginBorrowAsync` 
- `MarginRepayAsync`
Based on the official [documentation](https://developers.binance.com/docs/margin_trading/borrow-and-repay/Margin-Account-Borrow-Repay), which specifies a request weight of 1500 for these endpoints.

Fixed incorrect request weights

---

Binance.Net.UnitTests/Binance.Net.UnitTests.csproj
Binance.Net.UnitTests/Endpoints/General/GiftCard/CreateDualTokenGiftCard.txt
Binance.Net.UnitTests/Endpoints/General/GiftCard/CreateSingleTokenGiftCard.txt
Binance.Net.UnitTests/Endpoints/General/GiftCard/GetRsaPublicKey.txt
Binance.Net.UnitTests/Endpoints/General/GiftCard/GetTokenLimit.txt
Binance.Net.UnitTests/Endpoints/General/GiftCard/RedeemGiftCard.txt
Binance.Net.UnitTests/Endpoints/General/GiftCard/VerifyGiftCardByNumber.txt
Binance.Net.UnitTests/RestRequestTests.cs
Binance.Net/Binance.Net.xml
Binance.Net/Clients/GeneralApi/BinanceRestClientGeneralApiGiftCard.cs
Binance.Net/Converters/BinanceSourceGenerationContext.cs
Binance.Net/Interfaces/Clients/GeneralApi/IBinanceRestClientGeneralApiGiftCard.cs

- `POST /sapi/v1/giftcard/createCode`
- `POST /sapi/v1/giftcard/buyCode`
- `POST /sapi/v1/giftcard/redeemCode`
- `GET  /sapi/v1/giftcard/verify`
- `GET  /sapi/v1/giftcard/buyCode/token-limit`
- `GET  /sapi/v1/giftcard/cryptography/rsa-public-key`
While adding tests, a mapping issue was found in the `GetTokenLimitAsync` method, it was deserializing the response as a single object `BinanceGiftCardTokenLimit` instead of an array `BinanceGiftCardTokenLimit[]`. The response type has been corrected to handle array of items as returned by the API.
In apis that I implement I am trying to use `IEnumerable<T>`, but I noticed that `SourceGenerationContext` does only contain `T[]` and that some newer apis also use `T[]` instead of `IEnumerable<T>`.
Which approach is preferred?

Added Gift Card API tests & fixed deserialization error

---

Binance.Net.UnitTests/BinanceRestIntegrationTests.cs
Binance.Net/Binance.Net.xml
Binance.Net/Clients/CoinFuturesApi/BinanceRestClientCoinFuturesApiAccount.cs
Binance.Net/Interfaces/Clients/CoinFuturesApi/IBinanceRestClientCoinFuturesApiAccount.cs

'Page' param added to the GetIncomeHistory method in futures coin account client accordingly to the Binance reast api documentation: 
https://developers.binance.com/docs/derivatives/coin-margined-futures/account/rest-api/Get-Income-History

'Page' param added to the GetIncomeHistory method in futures coin account client
