Binance.Net/Objects/Binance24hPrice.cs

did a test with https://www.binance.com/api/v1/ticker/24hr?symbol=ETHBTC and saw that symbol is included in the result

Add Symbol property

---

Binance.Net/BinanceClient.cs
Binance.Net/IBinanceClient.cs

iinterface to mock the client on different unit / integration tests.

extracted BinanceClient into an interface

---

Binance.Net/BinanceClient.cs
Binance.Net/Objects/BinanceSymbolFilter.cs
Binance.Net/Objects/BinanceTrade.cs

Added error handling without code
fix BinanceSymbolPercentPriceFilter.AveragePriceMinutes decimal to int
Added QuoteQuantity to MyTrades

Fixed found issues

---

Binance.Net/BinanceClient.cs
Binance.Net/Interfaces/IBinanceClient.cs
Binance.Net/Objects/BinanceAveragePrice.cs

Added GetCurrentAvgPrice Method

GetCurrentAvgPrice Endpoint

---

Binance.Net/Binance.Net.xml
Binance.Net/BinanceFuturesSocketClient.cs
Binance.Net/BinanceHelpers.cs
Binance.Net/BinanceSocketClient.cs
Binance.Net/Converters/OrderTypeConverter.cs
Binance.Net/Converters/SymbolFilterConverter.cs
Binance.Net/Converters/TimeInForceConverter.cs
Binance.Net/Converters/WorkingTypeConverter.cs
Binance.Net/Interfaces/IBinanceFuturesSocketClient.cs
Binance.Net/Interfaces/IBinanceSocketClient.cs
Binance.Net/Objects/BinanceFuturesPosition.cs
Binance.Net/Objects/BinanceFuturesStreamAccountInfo.cs
Binance.Net/Objects/BinanceFuturesStreamLiquidation.cs
Binance.Net/Objects/BinanceFuturesStreamMarkPrice.cs
Binance.Net/Objects/BinanceFuturesStreamOrderBookDepth.cs
Binance.Net/Objects/BinanceFuturesStreamOrderUpdate.cs
Binance.Net/Objects/BinanceFuturesSymbol.cs
Binance.Net/Objects/BinanceStreamMiniTick.cs
Binance.Net/Objects/BinanceStreamTick.cs
Binance.Net/Objects/BinanceSymbolFilter.cs
Binance.Net/Objects/Enums.cs

Alpha futures fixes

---

Binance.Net/Binance.Net.xml
Binance.Net/BinanceFuturesClient.cs
Binance.Net/Objects/Futures/FuturesData/BinanceFuturesCancelAllOrders.cs

I've added the command to cancel all orders.
I'm using Rider on a Mac, so unfortunately it looks like a lot of changes because it strips white spaces at the end of lines, but the changes are very small:
- A new class for the return type
- A new entry for the command path
- The command itself

added cancel all orders.

---

Binance.Net/Binance.Net.xml
Binance.Net/BinanceFuturesClient.cs

I have added the CancelMultiple command as well.

Cancel multiple command added.

---

Binance.Net/Binance.Net.xml
Binance.Net/Interfaces/SubClients/IBinanceClientBrokerage.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerFuturesCommissionRebate.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageAddIpRestrictionResult.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageEnableLeverageTokenResult.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageFuturesAssetInfo.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageFuturesRebate.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageFuturesType.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageIpRestriction.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageMarginAssetInfo.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageSpotAssetInfo.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageSubAccount.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageSubAccountApiKey.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageSubAccountCoinFuturesCommission.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageSubAccountCommission.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageSubAccountDepositStatus.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageSubAccountDepositTransaction.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageTransferFuturesResult.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageTransferFuturesTransaction.cs
Binance.Net/SubClients/BinanceClientBrokerage.cs

Support latest changes: https://binance-docs.github.io/Brokerage-API/Change_Log/

Brokerage API updates

---

Binance.Net/Objects/Spot/MarketStream/BinanceStreamBookPrice.cs

add missing UpdateId at BinanceStreamBookPrice
> was accidentally deleted by the last update

add missing

---

Binance.Net/Binance.Net.xml
Binance.Net/Converters/BrokerageAccountTypeConverter.cs
Binance.Net/Converters/BrokerageTransferTransactionStatusConverter.cs
Binance.Net/Enums/BrokerageAccountType.cs
Binance.Net/Enums/BrokerageTransferTransactionStatus.cs
Binance.Net/Interfaces/SubClients/IBinanceClientBrokerage.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageTransferFuturesTransaction.cs
Binance.Net/Objects/Brokerage/SubAccountData/BinanceBrokerageTransferTransactionUniversal.cs
Binance.Net/SubClients/BinanceClientBrokerage.cs

Support latest changes (2020.10.12 - 2020.12.10): https://binance-docs.github.io/Brokerage-API/Change_Log/

Brokerage universal transfer methods

---

Binance.Net/SubClients/Spot/BinanceClientSpotOrders.cs

GET /api/v3/orderList (HMAC SHA256)
using origClientOrderId in stead listClientOrderId
relate to issue: #697

update query OCO to latest official Binance api

---

Binance.Net/Objects/Spot/MarginData/BinanceInterestRateHistory.cs

Deserialization was failing because of this property name

Fixed DailyInterest deserialization

---

Binance.Net/BinanceApiAddresses.cs

Updated SocketClientAddress for Test Network

---

Binance.Net/Binance.Net.xml
Binance.Net/Interfaces/SubClients/Futures/IBinanceClientFuturesOrders.cs
Binance.Net/Objects/Futures/FuturesData/BinanceFuturesBatchOrder.cs
Binance.Net/Objects/Futures/FuturesData/BinanceFuturesCancelOrder.cs
Binance.Net/Objects/Futures/FuturesData/BinanceFuturesOrder.cs
Binance.Net/Objects/Futures/FuturesData/BinanceFuturesPlacedOrder.cs
Binance.Net/SubClients/Futures/BinanceClientFuturesOrder.cs

Added missing `priceProtect`

---

Binance.Net/Binance.Net.xml
Binance.Net/Interfaces/SubClients/Futures/IBinanceClientFuturesOrders.cs
Binance.Net/SubClients/Futures/BinanceClientFuturesOrder.cs

Removed `newClientOrderId` from Futures

---

Binance.Net/Binance.Net.xml
Binance.Net/Interfaces/IBinanceClient.cs

IBinanceClient is missing Fiat subclient

Add Fiat subclient to IBinanceClient

---

Binance.Net/Binance.Net.xml
Binance.Net/Interfaces/SubClients/Futures/IBinanceClientFuturesAccount.cs
Binance.Net/Interfaces/SubClients/Futures/IBinanceClientFuturesCoinAccount.cs
Binance.Net/Interfaces/SubClients/Futures/IBinanceClientFuturesUsdtAccount.cs
Binance.Net/Objects/Futures/FuturesData/BinanceFuturesAccountUserCommissionRate.cs
Binance.Net/SubClients/Futures/Coin/BinanceClientFuturesCoinAccount.cs
Binance.Net/SubClients/Futures/Usdt/BinanceClientFuturesUsdtAccount.cs

https://binance-docs.github.io/apidocs/delivery/en/#user-commission-rate-user_data
https://binance-docs.github.io/apidocs/futures/en/#user-commission-rate-user_data

Add userCommissionRate

---

Binance.Net/Converters/AccountTypeConverter.cs
Binance.Net/Enums/AccountType.cs

Add missing Binance.Net.Enums.AccountType.TRD_GRP_002

---

Binance.Net/Interfaces/IBinanceBalance.cs
Binance.Net/Objects/Models/Spot/BinanceAccountInfo.cs
Binance.Net/Objects/Models/Spot/Socket/BinanceStreamPositionsUpdate.cs

Added Balance Interface IBinanceBalance

---

Binance.Net/Enums/KlineInterval.cs

https://github.com/JKorf/Binance.Net/issues/1057

Add milliseconds to KlineInterval enum

---

Binance.Net/Objects/Models/Spot/Lending/BinanceFlexibleProductPosition.cs

Tier Annual Interest Rate

---

Binance.Net/Clients/GeneralApi/BinanceClientGeneralApiLending.cs
Binance.Net/Interfaces/Clients/GeneralApi/IBinanceClientGeneralApiLending.cs

Asset is not mandatory and all positions can be returned in 1 request.

Parameters: GetFlexibleProductPositionAsync

---

Binance.Net/Binance.Net.xml
Binance.Net/Clients/SpotApi/BinanceClientSpotApiAccount.cs
Binance.Net/Interfaces/Clients/SpotApi/IBinanceClientSpotApiAccount.cs
Binance.Net/Objects/Models/Spot/Margin/BinanceInterestMarginData.cs

As defined in the documentation
https://binance-docs.github.io/apidocs/spot/en/#query-cross-margin-fee-data-user_data

Add Endpoint: query-cross-margin-fee-data

---

Binance.Net/Clients/SpotApi/BinanceClientSpotApiExchangeData.cs

```cs
limit?.ValidateIntBetween(nameof(limit), 1, 1000);
```
=>
```cs
limit?.ValidateIntBetween(nameof(limit), 1, 1500);
```

Fixes `GetKlinesAsync`

---

Binance.Net/Interfaces/Clients/SpotApi/IBinanceClientSpotApiAccount.cs

https://github.com/JKorf/Binance.Net/issues/1088

Clarify usage

---

Binance.Net/Binance.Net.xml
Binance.Net/Objects/Models/Futures/Socket/BinanceFuturesStreamAccountInfo.cs

BalanceChange (bc) to be deserialized from JSON

Added new balance change field

---

Binance.Net/Converters/SymbolFilterConverter.cs

Fixes max position writing empty strings

Fix Max Position Filter

---

Binance.Net/Converters/OrderRejectReasonConverter.cs
Binance.Net/Enums/OrderRejectReason.cs

Fixes https://github.com/JKorf/Binance.Net/issues/1143

Add STOP_PRICE_WOULD_TRIGGER_IMMEDIATELY Order Reject Reason

---

Binance.Net.UnitTests/BinanceSocketClientTests.cs
Binance.Net/Clients/UsdFuturesApi/BinanceSocketClientUsdFuturesStreams.cs
Binance.Net/Interfaces/Clients/UsdFuturesApi/IBinanceSocketClientUsdFuturesStreams.cs
Binance.Net/Objects/Models/Futures/Socket/BinanceFuturesStreamContinuousKline.cs

- Add BinanceStreamContinuousKlineData type
- Breaking change: change SubscribeToContinuousContractKlineUpdatesAsync signature to use the new type

Fix for #1163:

---

Binance.Net/Binance.Net.csproj
Binance.Net/Binance.Net.xml
Binance.Net/Clients/GeneralApi/BinanceClientGeneralApiSubAccount.cs
Binance.Net/Interfaces/Clients/GeneralApi/IBinanceClientGeneralApiSubAccount.cs
README.md

The current endpoints were discontinued in Jan 2023

Updated subaccount ip restriction endpoints

---

Binance.Net/Converters/SymbolFilterConverter.cs
Binance.Net/Converters/SymbolFilterTypeConverter.cs
Binance.Net/Enums/SymbolFilterType.cs
Binance.Net/Objects/Models/Spot/BinanceSymbolFilter.cs

Fixes https://github.com/JKorf/Binance.Net/issues/1224 and adds `MAX_NUM_ICEBERG_ORDERS`

Fix symbol filters add iceberg order

---

Binance.Net/Enums/AccountType.cs

Ref: https://binance-docs.github.io/apidocs/spot/en/#public-api-definitions
Fixes: https://github.com/JKorf/Binance.Net/issues/1263

Added missing Account and Symbol Permissions

---

Binance.Net/Binance.Net.xml
Binance.Net/Objects/Models/Spot/BinancePayTrade.cs

Added new json fileds
https://binance-docs.github.io/apidocs/spot/en/#get-pay-trade-history-user_data

Added PayerInfo and ReceiverInfo

---

Binance.Net/Objects/Options/BinanceRestOptions.cs
Binance.Net/Objects/Options/BinanceSocketOptions.cs

Info:
https://www.binance.com/en/support/announcement/binance-spot-api-to-increase-request-weight-limits-9820396bf54644c39e666b4780622846
https://www.binance.com/en/support/announcement/binance-spot-api-to-increase-single-account-order-rate-limit-a9eb5f629afd46b48a4f3f24d31b9bb5

Update Default Limits

---

Binance.Net.UnitTests/SocketSubscriptionTests.cs
Binance.Net.UnitTests/Subscriptions/UsdFutures/TradeUpdate.txt
Binance.Net/Binance.Net.xml
Binance.Net/Clients/UsdFuturesApi/BinanceSocketClientUsdFuturesApi.cs
Binance.Net/Interfaces/Clients/UsdFuturesApi/IBinanceSocketClientUsdFuturesApi.cs
Binance.Net/Objects/Models/Futures/Socket/BinanceFuturesStreamTradeUpdate.cs
Binance.Net/Objects/Sockets/Subscriptions/BinanceUsdFuturesUserDataSubscription.cs

https://www.binance.com/en/support/announcement/introducing-trade-lite-for-usd%E2%93%A2-m-futures-websocket-2024-09-03-f2809259702b46f7abdc9c97b977908f
https://developers.binance.com/docs/derivatives/usds-margined-futures/user-data-streams/Event-Trade-Lite

Add TRADE_LITE for USD-M Futures websocket

---

Binance.Net/Binance.Net.xml
Binance.Net/Objects/Models/Spot/BinanceUserAsset.cs

Added some missing fields (https://developers.binance.com/docs/wallet/capital)

Add contract address and URL properties to BinanceNetwork model

---

Binance.Net.UnitTests/BinanceRestIntegrationTests.cs
Binance.Net/Binance.Net.xml
Binance.Net/Clients/SpotApi/BinanceRestClientSpotApiAccount.cs
Binance.Net/Interfaces/Clients/SpotApi/IBinanceRestClientSpotApiAccount.cs

New docs: https://developers.binance.com/docs/wallet/asset/query-user-wallet-balance

Add quote-Asset param

---

Binance.Net/Binance.Net.xml
Binance.Net/Clients/SpotApi/BinanceRestClientSpotApi.cs
Binance.Net/Clients/SpotApi/BinanceRestClientSpotApiTrading.cs
Binance.Net/Converters/BinanceSourceGenerationContext.cs
Binance.Net/Enums/SymbolFilterType.cs
Binance.Net/Objects/Internal/BinanceSocketRequest.cs
Binance.Net/Objects/Models/BinanceOrderBookEntry.cs
Binance.Net/Objects/Models/Futures/AlgoOrders/BinanceAlgoOrder.cs
Binance.Net/Objects/Models/Futures/BinanceFuturesExchangeInfo.cs
Binance.Net/Objects/Models/Futures/BinanceFuturesOrder.cs
Binance.Net/Objects/Models/Spot/BinanceEventOrderBook.cs
Binance.Net/Objects/Models/Spot/BinanceExchangeInfo.cs
Binance.Net/Objects/Models/Spot/BinanceOrderBook.cs
Binance.Net/Objects/Sockets/BinanceSocketQueryResponse.cs

Unfortunately, due to too low network, I was not able to perform real tests.

Add NullableEnumConverterFactory
